---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-operator
  namespace: d8-registry-operator
  {{- include "helm_lib_module_labels" (list . (dict "app" "registry-operator")) | nindent 2 }}
spec:
  {{- include "helm_lib_deployment_strategy_and_replicas_for_ha" . | nindent 2 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: registry-operator
  template:
    metadata:
      labels:
        app: registry-operator
    spec:
      {{- include "helm_lib_priority_class" (tuple . "system-cluster-critical") | nindent 6 }}
      {{- include "helm_lib_pod_anti_affinity_for_ha" (list . (dict "app" "registry-operator")) | nindent 6 }}
      {{- include "helm_lib_node_selector" (tuple . "system") | nindent 6 }}
      {{- include "helm_lib_tolerations" (tuple . "system") | nindent 6 }}
      {{- include "helm_lib_module_pod_security_context_run_as_user_deckhouse" . | nindent 6 }}
      serviceAccountName: registry-operator
      imagePullSecrets:
      - name: deckhouse-registry
      containers:
      - name: controller
        {{- include "helm_lib_module_container_security_context_read_only_root_filesystem" . | nindent 8 }}
        image: {{ include "helm_lib_module_image" (list . "controller") }}
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_LEVEL
          value: {{ .Values.registryOperator.logLevel | default "info" | quote }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            {{- include "helm_lib_module_ephemeral_storage_only_logs" . | nindent 12 }}
{{- if not ( .Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
            memory: 128Mi
            cpu: 100m
{{- end }}
