name: Build

on:
  push:

env:
  CI_COMMIT_REF_NAME: ${{ github.ref_name }}
  MODULE_NAME: registry-operator

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run linter
        uses: deckhouse/modules-actions/lint@main

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: deckhouse/modules-actions/setup@main
        with:
          registry: ghcr.io
          registry-login: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: deckhouse/modules-actions/build@main
        with:
          module-source: ghcr.io/${{ github.repository_owner }}
          module-name: ${{ env.MODULE_NAME }}
          module-tag: ${{ github.ref_name }}
